midcity/midcity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('midcityapp.urls')),
    path('', include('accounts.urls')),
    path('api/', include([
    path('', include('midcityapp.api.urls')),
    ])),
]

midcity/midcityapp/urls.py
from django.urls import path, include

from .views import *
from . import views

app_name = "events"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('contactus', views.contactus, name='contactus'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('organization/dashboard', include([
        path('', DashboardView.as_view(), name='organization-dashboard'),
        path('all-volunteerships', VolunteershipsListView.as_view(), name='organization-all-volunteerships'),
        path('volunteerships/<int:event_id>', VolunteershipPerEventView.as_view(), name='organization-dashboard-volunteerships'),
        path('mark-filled/<int:event_id>', filled, name='event-mark-filled'),
        path('attendance/<pk>/edit/', views.attendance, name='attendance'),
    ])),
    path('apply-event/<int:event_id>', ApplyEventView.as_view(), name='apply-event'),
    path('volunteerships/<int:user_id>', VolunteershipPerUserView.as_view(), name='myvolunteerships'),
    path('events', EventListView.as_view(), name='events'),
    path('events/<int:id>', EventDetailsView.as_view(), name='events-detail'),
    path('organization/events/create', EventCreateView.as_view(), name='organization-events-create'),

]

midcity/templates/events/aboutus.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}

{% block content %}


    <section class="event-form-section event-form-section--image">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="event-form-box">
                        <h2 class="heading">What we do:</h2>
                        <h5>This is information about our organization</h5>
                        <h5>Our History</h5>
                        <h5>Our Mission</h5>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

midcity/templates/events/contactus.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}

{% block content %}


    <section class="event-form-section event-form-section--image">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="event-form-box">
                        <h2 class="heading">Contact us at:</h2>
                        <h5>Email:midcity@email.com</h5>
                        <h5>Phone number:000-000-0000</h5>
                        <h5>Address:midcity office omaha</h5>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

midcity/templates/events/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    {{ title }}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Add a new Event</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    <strong>{{ field.name }} {{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                    <form id="event-main-form" method="post" action="" class="event-add-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12">
                                <h4>Event details</h4>
                                <hr>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="title">Event Title</label>
                                <input id="title" name="title" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="text">Event Description</label>
                                <textarea id="text" name="description" rows="5" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <label for="location">Location</label>
                                <input id="location" name="location" type="text" placeholder="e.g. Rio de Janeiro"
                                       class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="category">Category</label>
                                <select id="category" name="category" placeholder="Choose category"
                                        class="form-control select2">
                                    <option value="Community">Community</option>
                                    <option value="Arts & Culture">Arts & Culture</option>
                                    <option value="Chidren & Youth">Chidren & Youth</option>
                                    <option value="Environment">Environment</option>
                                    <option value="Animals">Animals</option>
                                    <option value="Faith-Based">Faith-Based</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6 form-group">
                                <label for="validity">Event Date</label>
                                <input id="validity" name="last_date" type="date" class="form-control">
                                <div class="row">
                                    <div class="col-xl-6 form-group">
                                        <label for="validity">Number of Volunteers Required</label>
                                        <input id="volunteers_required" name="volunteers_required" type="number" class="form-control">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <hr class="margin-bottom--big">
                                    </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <h4>Organization details</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="company_name">Organization name</label>
                                <input id="company_name" name="company_name" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 form-group">
                                <label for="company_description">Organization Description</label>
                                <textarea id="company_description" name="company_description" rows="3"
                                          class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <hr>
                                <div class="checkbox text-center">
                                    <label>
                                        <input type="checkbox"> I agree with the <a href="#">Terms and conditions</a>.
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 text-center">
                                <hr>
                                <button type="submit" class="btn btn-outline-white-primary"><i class="fa fa-magic"></i>
                                    Save and publish
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

midcity/templates/events/details.html
{% extends 'base.html' %}
{% load static %}
{% load is_already_applied %}
{% block title %}
    Event details
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <h1 class="heading">{{ event.title }}<br>
                <small>for <a href="#">{{ event.company_name }}</a></small>
            </h1>
            <div class="event-detail-description"><i class="fa fa-map-marker event__location"> </i>
                {{ event.location }} | Posted {{ event.created_at|timesince }} |
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <h3>Category: {{ event.category }}</h3>
                    <h5 class="text-info">Event date: {{ event.last_date|date }}</h5>
                    <blockquote class="blockquote">
                        <p>{{ event.description }}</p>
                    </blockquote>
                {% if request.user.is_authenticated and request.user.role == 'volunteer' %}
                    <div class="event-detail__apply-bottom">
                        {% if request.user.is_authenticated %}
                            {% is_already_applied event request.user as is_applied %}
                            {% if is_applied %}
                                <input type="button" class="btn btn-outline-success" value="Already Signed up"/>
                            {% else %}
                                <form action="{% url 'events:apply-event' event.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="event" value="{{ event.id }}">
                                    <input type="submit" class="btn btn-outline-white-primary"
                                           value="Sign up for this event"/>
                                </form>
                            {% endif %}
                        {% else %}
                            <form action="{% url 'events:apply-event' event.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="event" value="{{ event.id }}">
                                <input type="submit" class="btn btn-outline-white-primary"
                                       value="Sign up for this event"/>
                            </form>
                        {% endif %}
                    </div>
                {% else %}
                {% endif %}

                </div>
                <div class="col-lg-1"></div>
                <div class="col-lg-3">
                    <h4>About {{ event.company_name }}</h4>
                    <p class="event-detail__company-description">{{ event.company_description }}</p>
                    </p>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

midcity/templates/events/events.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All Events
{% endblock %}

{% block content %}

    <section class="event-form-section event-form-section--compressed">
        <div class="container">
            <h4 class="heading">Find an <span class="accent">Event </span> to <span class="accent">Volunteer</span></h4>
            <form id="event-main-form" method="get" action="#" class="event-main-form">
                <div class="controls">
                    <div class="row align-items-end">
                        <div class="col-sm-1 col-lg-2"></div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="profession">Profession</label>
                            <input type="text" id="profession" name="profession"
                                   placeholder="Profession you are looking for" class="form-control">
                        </div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="location">Location</label>
                            <input type="text" id="location" name="location" placeholder="Any particular location?"
                                   value="Bay Area" class="form-control">
                        </div>
                        <div class="col-sm-1 col-lg-2 form-group">
                            <button type="submit" name="name"
                                    class="btn btn-outline-white-primary event-main-form__button">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <section>
        <div class="container">
            <h3 class="heading">We have found <span class="accent">{{ events.count }}</span> events</h3>
            {% for event in events %}
                <div class="event-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/company-1.png' %}"
                                         alt="Ipsioou " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="event__title"><a
                                            href="{% url 'events:events-detail' event.id %}">{{ event.title }}</a></h4>
                                    <p class="event__company">
                                        {{ event.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker event__location"></i>
                            {{ event.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ event.created_at|timesince }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}

midcity/templates/events/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All events
{% endblock %}

{% block content %}

    <section class="event-form-section event-form-section--compressed">
        <div class="container">
            <h4 class="heading">Find an <span class="accent">Event </span> to <span class="accent">Volunteer</span></h4>
            <form id="event-main-form" method="get" action="#" class="event-main-form">
                <div class="controls">
                    <div class="row align-items-end">
                        <div class="col-sm-1 col-lg-2"></div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="profession">Event</label>
                            <input type="text" id="position" name="position"
                                   placeholder="Event you are looking for" class="form-control">
                        </div>
                        <div class="col-sm-5 col-lg-4 form-group">
                            <label for="location">Location</label>
                            <input type="text" id="location" name="location" placeholder="Any particular location?"
                                   value="" class="form-control">
                        </div>
                        <div class="col-sm-1 col-lg-2 form-group">
                            <button type="submit" name="name"
                                    class="btn btn-outline-white-primary event-main-form__button">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <section>
        <div class="container">
            <h3 class="heading">We have found <span class="accent">{{ events.count }}</span> events</h3>
            {% for event in events %}
                <div class="event-listing  ">
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="row">
                                <div class="col-2">
                                    <img src="{% static 'img/company-1.png' %}"
                                         alt="Ipsioou " class="img-fluid">
                                </div>
                                <div class="col-10">
                                    <h4 class="event__title"><a
                                            href="{% url 'events:events-detail' event.id %}">{{ event.title }}</a></h4>
                                    <p class="event__company">
                                        {{ event.company_name }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 col-md-3 col-lg-2 ml-auto"><i class="fa fa-map-marker event__location"></i>
                            {{ event.location }}
                        </div>
                        <div class="col-10 col-md-3 col-lg-3 ml-auto">
                            <p>Posted {{ event.created_at|timesince }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if is_paginated %}
                <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}"
                                           class="page-link">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&laquo;</a>
                                    </li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active">
                                            <a class="page-link">{{ i }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </div>
    </section>

{% endblock %}