midcity/accounts/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from midcityapp.views import EditProfileView
from .views import *

app_name = "accounts"

urlpatterns = [
    path('volunteer/register', RegisterVolunteerView.as_view(), name='volunteer-register'),
    path('organization/register', RegisterOrganizationView.as_view(), name='organization-register'),
    path('volunteer/profile/update', EditProfileView.as_view(), name='organization-profile-update'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('login', LoginView.as_view(), name='login'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

midcity/midcity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('midcityapp.urls')),
    path('', include('accounts.urls')),
    path('api/', include([
    path('', include('midcityapp.api.urls')),
    ])),
]

midcity/midcityapp/urls.py
from django.urls import path, include

from .views import *
from . import views

app_name = "events"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('contactus', views.contactus, name='contactus'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('organization/dashboard', include([
        path('', DashboardView.as_view(), name='organization-dashboard'),
        path('all-volunteerships', VolunteershipsListView.as_view(), name='organization-all-volunteerships'),
        path('volunteerships/<int:event_id>', VolunteershipPerEventView.as_view(), name='organization-dashboard-volunteerships'),
        path('mark-filled/<int:event_id>', filled, name='event-mark-filled'),
        path('attendance/<pk>/edit/', views.attendance, name='attendance'),
    ])),
    path('apply-event/<int:event_id>', ApplyEventView.as_view(), name='apply-event'),
    path('volunteerships/<int:user_id>', VolunteershipPerUserView.as_view(), name='myvolunteerships'),
    path('events', EventListView.as_view(), name='events'),
    path('events/<int:id>', EventDetailsView.as_view(), name='events-detail'),
    path('organization/events/create', EventCreateView.as_view(), name='organization-events-create'),

]

midcity/midcityapp/views/home.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView
from django.db.models import F
from django.shortcuts import render



from ..forms import ApplyEventForm
from ..models import Event, Volunteership


class HomeView(ListView):
    model = Event
    template_name = 'home.html'
    context_object_name = 'events'

    def get_queryset(self):
        return self.model.objects.all()[:6]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trendings'] = self.model.objects.filter(created_at__month=timezone.now().month)[:3]
        return context


class SearchView(ListView):
    model = Event
    template_name = 'events/search.html'
    context_object_name = 'events'

    def get_queryset(self):
        return self.model.objects.filter(location__contains=self.request.GET['location'],
                                         title__contains=self.request.GET['position'])


class EventListView(ListView):
    model = Event
    template_name = 'events/events.html'
    context_object_name = 'events'
    paginate_by = 5


class EventDetailsView(DetailView):
    model = Event
    template_name = 'events/details.html'
    context_object_name = 'event'
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        obj = super(EventDetailsView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Event doesn't exists")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            # redirect here
            raise Http404("Event doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class ApplyEventView(CreateView):
    model = Volunteership
    form_class = ApplyEventForm
    slug_field = 'event_id'
    slug_url_kwarg = 'event_id'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            messages.info(self.request, 'Successfully applied for the event!')
            return self.form_valid(form)
        else:
            return HttpResponseRedirect(reverse_lazy('events:home'))

    def get_success_url(self):
        return reverse_lazy('events:events-detail', kwargs={'id': self.kwargs['event_id']})


    def form_valid(self, form):
        # check if user already applied
        volunteership = Volunteership.objects.filter(user_id=self.request.user.id, event_id=self.kwargs['event_id'])
        if volunteership:
            messages.info(self.request, 'You have already signed up for this event')
            return HttpResponseRedirect(self.get_success_url())
        # save volunteership
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

def contactus(request):
    return render(request, 'events/contactus.html', {'events': contactus})

def aboutus(request):
    return render(request, 'events/aboutus.html', {'events': aboutus})

midcity/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %} {% endblock %} - Django Events</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet"
          href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
          href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet"
          href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet"
          href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}"
          id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block styles %}{% endblock %}
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
<!-- navbar-->
<header class="header">
    <nav class="navbar navbar-expand-lg" style="background: #07637a">
        <div class="container">
            <a href="/" class="navbar-brand">
                <img src="{% static 'img/logo-small.png' %}" alt="logo" class="d-none d-lg-block">
                <span class="sr-only">Home</span>
            </a>
            <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler navbar-toggler-right">Menu<i class="fa fa-bars"></i>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a href="/" class="nav-link">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'events:aboutus' %}" class="nav-link">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'events:contactus' %}" class="nav-link">Contact</a>
                    </li>
                    {% if request.user.is_authenticated and request.user.role == 'organization' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/company-1.png' %}"
                                             alt="company image"
                                             class="img-fluid">
                                    </div>
                                </div>
                                {% if request.user.role == 'volunteer' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a href="{% url 'events:organization-dashboard' %}" class="dropdown-item">Dashboard</a>
                                <a href="{% url 'events:organization-all-volunteerships' %}" class="dropdown-item">Mark Attendance</a>
                                <a href="{% url 'events:organization-events-create' %}" class="dropdown-item">Post a new
                                    event </a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% elif request.user.is_authenticated and request.user.role == 'volunteer' %}
                        <li class="nav-item dropdown">
                            <a id="clientZone" href="#" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle has-img mb-3 mb-lg-0 mt-3 mt-lg-0">
                                <div class="client-menu-image">
                                    <div class="inner">
                                        <img src="{% static 'img/company-1.png' %}"
                                             alt="company image"
                                             class="img-fluid">
                                    </div>
                                </div>
                                {% if request.user.role == 'volunteer' %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.first_name }}
                                {% endif %}
                            </a>
                            <div aria-labelledby="clientZone" class="dropdown-menu">
                                <a href="{% url 'events:myvolunteerships' user.id %}" class="dropdown-item">My Events</a>
                                <a href="{% url 'accounts:organization-profile-update' %}" class="dropdown-item">Edit Profile</a>
                                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                            </div>
                        </li>
                    {% else %}

                        {% if user.is_superuser %}
                            <li class="nav-item" style="color: #fff">
                            <a href="{% url 'accounts:logout' %}" class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i>ADMIN Logout
                            </a>
                        </li>
                            {% else %}
                        <li class="nav-item dropdown">
                            <a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle"><i class="fa fa-signing"></i>Register
                            </a>
                            <div aria-labelledby="pages" class="dropdown-menu">
                                <a href="{% url 'accounts:volunteer-register' %}" class="dropdown-item">Volunteer</a>
                                <a href="{% url 'accounts:organization-register' %}" class="dropdown-item">Organization</a>
                            </div>
                        </li>
                        <li class="nav-item" style="color: #fff">
                            <a href="{% url 'accounts:login' %}" class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                                <i class="fa fa-sign-in"></i>Login
                            </a>
                        </li>
                        {% endif %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<div>
    {% if messages %}

        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
{#            <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>#}
        {% endfor %}

    {% endif %}
    {% block content %} {% endblock %}
</div>
<footer class="footer">
    <div class="footer__copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-md-left text-center">
                    <p>&copy;2019 MidCity</p>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>

{% block javascripts %}{% endblock %}

</body>

</html>

midcity/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock %}

{% block content %}

    
    <section class="event-form-section event-form-section--image">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="event-form-box">
                        <h2 class="heading">Find an <span class="accent">Event</span> to
                            <span class="accent">Volunteer</span>
                        </h2>
                        <form id="event-main-form" method="get" action="{% url 'events:searh' %}" class="event-main-form">
                            <div class="controls">
                                <div class="row align-items-center">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="profession">Event</label>
                                            <input type="text" id="profession" name="position"
                                                   placeholder="Event you are looking for" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label for="location">Location</label>
                                            <input type="text" id="location" name="location"
                                                   placeholder="Any particular location?" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit"
                                                class="btn btn-outline-white-primary event-main-form__button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="bg-light-gray">
        <div class="container">
            <h3 class="heading">Featured events</h3>
            <div class="row featured align-items-stretch">
                {% for event in events %}
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="box-image-text bg-visible full-height">
                            <div class="top">
                                <a href="{% url 'events:events-detail' event.id %}">
                                    <div class="image">
                                        <img src="{% static 'img/featured1.jpg' %}" alt="" class="img-fluid">
                                    </div>
                                    <div class="bg"></div>
                                    <div class="logo">
                                        <img src="{% static 'img/company-1.png' %}" alt="" style="max-width: 80px;">
                                    </div>
                                </a>
                            </div>
                            <div class="content">
                                <h5><a href="{% url 'events:events-detail' event.id %}">{{ event.title }}</a></h5>
                                <p class="featured__details"><i class="fa fa-map-marker event__location"></i>
                                    {{ event.location }}
                                <p>{{ event.description }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}