midcity/midcity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('midcityapp.urls')),
    path('', include('accounts.urls')),
    path('api/', include([
    path('', include('midcityapp.api.urls')),
    ])),
]

midcity/midcityapp/urls.py
from django.urls import path, include

from .views import *
from . import views

app_name = "events"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('contactus', views.contactus, name='contactus'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('organization/dashboard', include([
        path('', DashboardView.as_view(), name='organization-dashboard'),
        path('all-volunteerships', VolunteershipsListView.as_view(), name='organization-all-volunteerships'),
        path('volunteerships/<int:event_id>', VolunteershipPerEventView.as_view(), name='organization-dashboard-volunteerships'),
        path('mark-filled/<int:event_id>', filled, name='event-mark-filled'),
        path('attendance/<pk>/edit/', views.attendance, name='attendance'),
    ])),
    path('apply-event/<int:event_id>', ApplyEventView.as_view(), name='apply-event'),
    path('volunteerships/<int:user_id>', VolunteershipPerUserView.as_view(), name='myvolunteerships'),
    path('events', EventListView.as_view(), name='events'),
    path('events/<int:id>', EventDetailsView.as_view(), name='events-detail'),
    path('organization/events/create', EventCreateView.as_view(), name='organization-events-create'),

]

midcity/midcityapp/views/organization.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView
from django.shortcuts import render, get_object_or_404

from midcityapp.decorators import user_is_organization
from midcityapp.forms import CreateEventForm, VolunteershipForm
from midcityapp.models import Event, Volunteership
from accounts.models import User


class DashboardView(ListView):
    model = Event
    template_name = 'events/organization/dashboard.html'
    context_object_name = 'events'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_organization)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user_id=self.request.user.id)


class VolunteershipPerEventView(ListView):
    model = Volunteership
    template_name = 'events/organization/volunteerships.html'
    context_object_name = 'volunteerships'
    paginate_by = 5

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_organization)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Volunteership.objects.filter(event_id=self.kwargs['event_id']).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['event'] = Event.objects.get(id=self.kwargs['event_id'])
        return context


class EventCreateView(CreateView):
    model = None
    object = None
    template_name = 'events/create.html'
    form_class = CreateEventForm
    extra_context = {
        'title': 'Post New Event'
    }
    success_url = reverse_lazy('events:organization-dashboard')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('accounts:login')
        if self.request.user.is_authenticated and self.request.user.role != 'organization':
            return reverse_lazy('accounts:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(EventCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        # self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class VolunteershipsListView(ListView):
    model = Volunteership
    template_name = 'events/organization/all-volunteerships.html'
    context_object_name = 'volunteerships'

    def get_queryset(self):
        # events = Event.objects.filter(user_id=self.request.user.id)
        return self.model.objects.filter(event__user_id=self.request.user.id)


def attendance(request, pk):
    volunteership = get_object_or_404(Volunteership, pk=pk)
    if request.method == "POST":
        # update attendance
        form = VolunteershipForm(request.POST, instance=volunteership)
        if form.is_valid():
            volunteership = form.save(commit=False)
            volunteership.save()
            volunteerships = Volunteership.objects.filter()
            return render(request, 'events/organization/all-volunteerships.html',
                          {'volunteerships': volunteerships})
    else:
        # edit attendance
        form = VolunteershipForm(instance=volunteership)
    return render(request, 'events/organization/attendance.html', {'form': form})


@login_required(login_url=reverse_lazy('accounts:login'))
def filled(request, event_id=None):
    event = Event.objects.get(user_id=request.user.id, id=event_id)
    event.filled = True
    event.save()
    return HttpResponseRedirect(reverse_lazy('events:organization-dashboard'))

midcity/templates/events/organization/all-volunteerships.html
{% extends 'base.html' %}
{% block title %}
    Volunteerships
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">All volunteerships who signed up for your Events</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for volunteership in volunteerships %}
                    <div class="col-lg-4">
                        <div class="box volunteership">
                            <h4>{{ volunteership.user.get_full_name }}</h4>
                            <p><strong>Event: {{ volunteership.event.title }}</strong></p>
                            <p>
                                <span class="badge badge-light">Signed up on {{ volunteership.created_at.astimezone }}</span>
                            </p>
                            <p><span class="badge badge-info">Attendance: {{ volunteership.attendance }}</span></p>
                            <a href="{% url 'events:attendance' pk=volunteership.pk %}" class="btn btn-outline-success">Update Attendance</a>

                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'img/avatar.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% else %}
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

midcity/templates/events/organization/attendance.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Update Attendance</h1>
    <form method="POST" class="investment-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

midcity/templates/events/organization/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Dashboard
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">dashboard</h1>
                    <p class="lead text-center">All created Events</p>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-right mb-5"><a href="{% url 'events:organization-events-create' %}"
                                                          class="btn btn-outline-white-primary">
                    <i class="fa fa-plus"></i>Add new Event</a></div>
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-client-dashboard">
                            <thead>
                            <tr>
                                <th>Event title</th>
                                <th>Volunteers Required</th>
                                <th>Date posted</th>
                                <th>Date expiring</th>
                                <th>Volunteerships</th>
{#                                <th>Actions</th>#}
                            </tr>
                            </thead>
                            <tbody>
                            {% for event in events %}

                                <tr>
                                    <th><a href="{% url 'events:events-detail' event.id %}">{{ event.title }}</a>
                                    </th>
                                    <td>  <span class="badge badge-warning"><h5>{{ event.volunteers_required }} </h5></span> </td>
                                    <td>{{ event.created_at }}</td>
                                    <td>{{ event.last_date }}</td>
                                    <td>
                                        <a href="{% url 'events:organization-dashboard-volunteerships' event.id %}"
                                           class="btn-success btn-block">
                                            <i class="fa fa-users"></i>{{ event.volunteerships.count }}
                                            <span class="hidden-xs hidden-sm">Volunteer Sign ups</span>
                                        </a>
                                    </td>
{#                                    <td>#}
{#                                        <a href="#" class="btn btn-outline-white-secondary">#}
{#                                            <i class="fa fa-edit"></i>Edit#}
{#                                        </a>#}
{#                                        <br>#}
{#                                        {% if event.filled %}#}
{#                                            <a href="{% url 'events:event-mark-filled' event.id %}"#}
{#                                               class="btn btn-outline-white-secondary">#}
{#                                                <i class="fa fa-check-circle-o"></i>#}
{#                                                <span class="hidden-xs hidden-sm">Filled</span>#}
{#                                            </a><br>#}
{#                                        {% else %}#}
{#                                            <a href="{% url 'events:event-mark-filled' event.id %}"#}
{#                                               class="btn btn-outline-white-secondary">#}
{#                                                <i class="fa fa-check-circle-o"></i>#}
{#                                                <span class="hidden-xs hidden-sm">Mark as </span>filled#}
{#                                            </a><br>#}
{#                                        {% endif %}#}
{#                                        <a href="#" class="btn btn-outline-white-secondary">#}
{#                                            <i class="fa fa-times-circle-o"></i>Delete#}
{#                                        </a>#}
{#                                    </td>#}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

midcity/templates/events/organization/volunteerships.html
{% extends 'base.html' %}
{% block title %}
    Volunteerships
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Volunteerships for the <span class="accent">{{ event.title }}</span> position</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for volunteership in volunteerships %}
                    <div class="col-lg-4">
                        <div class="box volunteership">
                            <h4>{{ volunteership.user.get_full_name }}</h4>
                            <p>
                                <span class="badge badge-light">Signed up on {{ volunteership.created_at.astimezone }}</span>
                            </p>
                            <p><span class="badge badge-info">Attendance: {{ volunteership.attendance }}</span></p>
                            <a href="{% url 'events:attendance' pk=volunteership.pk %}" class="btn btn-outline-success">Update Attendance</a>
                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'img/avatar.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% else %}
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}